### ISSUE TITLE
An error occurs during use, but access using a proxy is normal. And does Twitter block IP addresses? Is there any solution to my situation?

### ISSUE THREAD

**Issue by chenxhong** [fa0311/twitter-openapi-typescript#93]
error message: 
/home/node_modules/twitter-openapi-typescript-generated/dist/runtime.js:416
        var _this = _super.call(this, msg) || this;
                           ^

Error [FetchError]: The request failed and the interceptors did not return an alternative response
    at new FetchError (/home/node_modules/twitter-openapi-typescript-generated/dist/runtime.js:416:28)
    at UserApi.<anonymous> (/home/node_modules/twitter-openapi-typescript-generated/dist/runtime.js:237:39)
    at step (/home/node_modules/twitter-openapi-typescript-generated/dist/runtime.js:72:23)
    at Object.throw (/home/node_modules/twitter-openapi-typescript-generated/dist/runtime.js:53:53)
    at rejected (/home/node_modules/twitter-openapi-typescript-generated/dist/runtime.js:45:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: TypeError: fetch failed
      at node:internal/deps/undici/undici:12344:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    cause: AggregateError
        at internalConnectMultiple (node:net:1114:18)
        at internalConnectMultiple (node:net:1177:5)
        at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      code: 'ETIMEDOUT',
      [errors]: [
        Error: connect ETIMEDOUT 162.125.8.1:443
            at createConnectionError (node:net:1634:14)
            at Timeout.internalConnectMultipleTimeout (node:net:1685:38)
            at listOnTimeout (node:internal/timers:575:11)
            at process.processTimers (node:internal/timers:514:7) {
          errno: -110,
          code: 'ETIMEDOUT',
          syscall: 'connect',
          address: '162.125.8.1',
          port: 443
        },
        Error: connect ENETUNREACH 2a03:2880:f11b:83:face:b00c:0:25de:443 - Local (:::0)
            at internalConnectMultiple (node:net:1176:40)
            at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
            at listOnTimeout (node:internal/timers:575:11)
            at process.processTimers (node:internal/timers:514:7) {
          errno: -101,
          code: 'ENETUNREACH',
          syscall: 'connect',
          address: '2a03:2880:f11b:83:face:b00c:0:25de',
          port: 443
        }
      ]
    }
  }
}

**Comment by fa0311** [comment]
v0.0.40 is released. Is this problem still present?
